### ISSUE TITLE
A little tip

### ISSUE THREAD

**Issue by Magicianred** [francesco-maurella/js-mail-dadi#1]
it would be nice to have a loader. I mean when you press the button, the dice rolls for a while, then the dice stop and only at the end you see the result with the smiley face and the words "Hai vinto", "Hai pareggiato" or "Hai perso".
Now when you press the button you immediately see the result. I believe that if there was a bit of a wait, the effect would be better. And it is a little challenge of programming :)

Also in the readme you could put the link to the live site.

In any case, congratulations. Nice experiment.

**Comment by francesco-maurella** [comment]
Thank you for the feedback and the tip.
I fixed it with a setTimeout function :)
